### ISSUE TITLE
Support for newer Cura?

### ISSUE THREAD

**Issue by eyal0** [OctoPrint/OctoPrint-CuraEngineLegacy#10]
Why not support newer Cura?  Couldn't this plugin just detect which version of Cura is running and then use that to determine the right parameters for Cura?  That's how OctoPrint-Slic3r is doing it.

**Comment by foosel** [comment]
Completely (and I mean COMPLETELY) different way of modelling slicer profiles, calling parameters and so on. I and several other people spent a lot of time trying to keep up with Cura's developing back when they switched to the new model, and it turned out to be pretty much impossible to utilize from something like OctoPrint simply because the profiles (that you need to slice) are defined hierarchical, with at least until the most recent look at things about a year ago no way to create a full profile dump that could be imported and used in something like OctoPrint.

So a user would have to first import a whole bunch of profiles that depend on each other, then ensure to keep them updated, and then maybe, just maybe, it might work.

If you want to give it a shot, feel free, the intermediate WIP builds of the past attempts are still lying around in an archived repository on the OctoPrint orga if I'm not mistaken. I will not waste any more time on this, and I can only recommend to everyone else to not do that either unless there's a way to export *full* profiles from future Cura versions that makes this a bit less of a nightmare.
